src/auth/urls.py
from django.urls import path

from auth import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('twofactor/', views.two_factor, name='two_factor'),
    path('qrcode/', views.qrcode, name='qrcode'),
]

app_name = 'auth'

src/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('auth.urls')),
    path('users/', include('users.urls')),
]

src/users/urls.py
from django.urls import path

from users import views

urlpatterns = [
    path('me/', views.user_get, name='me'),
]

app_name = 'users'

src/users/models.py
from hashlib import md5

from django.contrib.auth.models import AbstractUser
from django.db import models

import pyotp


class User(AbstractUser):
    """
    User entity.
    """
    email = models.EmailField(unique=True)
    otp_secret = models.CharField(max_length=32)

    @property
    def avatar_url(self) -> str:
        avatar_hash = md5(self.email.encode()).hexdigest()
        return f'https://www.gravatar.com/avatar/{avatar_hash}?d=mp'
    
    @property
    def totp_uri(self):
        return 'otpauth://totp/2FA-Demo:{0}?secret={1}&issuer=2FA-Demo' \
            .format(self.username, self.otp_secret)

    def verify_totp(self, token):
        totp = pyotp.TOTP(self.otp_secret)
        return totp.verify(token, valid_window=2)

src/users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


@login_required
def user_get(request):
    return render(request, 'profile.html')

src/templates/base.html
<!doctype html>
<html>
  <head>
    <title>Bachelor TOTP</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
  </head>
  <body>
    
    <div class="container">
      {% include 'components/_navbar.html' %}
      <div class="container mt-3">
        {% include 'components/_messages.html' %}
      </div>
      <div class="container mt-3">
        {% block content %}
        {% endblock content %}
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

src/templates/components/_messages.html
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-info" role="alert">
      {{ message }}
    </div>
  {% endfor %}
{% endif %}

src/templates/components/_navbar.html
<nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Bachelor TOTP</a>
      {% if user.is_authenticated %}
        <a class="link-dark" href="{% url 'auth:logout' %}">Logout</a>
      {% else %}
        <a class="link-dark" href="{% url 'auth:login' %}">Login</a>
      {% endif %}
    </div>
  </nav>

src/templates/profile.html
{% extends 'base.html' %}

{% block content %}
  <div class="row">
    <div class="col-md-4">
      <img src="{{ user.avatar_url }}&s=300" class="rounded-circle">
    </div>
    <div class="col-md-8">
      Username: {{ user.username }} <br>
    </div>
  </div>
{% endblock content %}